### ISSUE TITLE
Nuxt 4 Support

### ISSUE THREAD

**Issue by offizium-berndstorath** [nuxt/eslint#479] opened 2024-08-14 09:49 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.15.0`
- Nuxt Version:     `3.12.4`
- CLI Version:      `3.12.0`
- Nitro Version:    `-`
- Package Manager:  `pnpm@9.7.0`
- Builder:          `-`
- User Config:      `future`, `compatibilityDate`, `devtools`, `modules`, `colorMode`
- Runtime Modules:  `@nuxtjs/i18n@8.3.3`, `@nuxtjs/tailwindcss@6.12.1`, `@pinia/nuxt@0.5.3`, `@eschricht/nuxt-color-mode@1.1.5`
- Build Modules:    `-`

### Package

None

### Reproduction

Package is `@nuxt/eslint-config` issue form is outdated

Use new Nuxt 4 Folder Structure

### Describe the bug

Component `Button` inside `app/components/base/Button.vue` throws error `Component name "Button" should always be multi-word.`.
Using the old folder structure this doesn't throw because it shouldnt as the component would be used as `BaseButton` (which is multi word)

**Comment by antfu** [comment] 2024-08-14 12:35
<img width="1614" alt="Screenshot 2024-08-14 at 14 34 36" src="https://github.com/user-attachments/assets/4e73be39-aa05-4ab3-b16f-123a6e9d917e">


It seems to me the configs are correctly inferred. Please provide a minimal reproduction, thanks

**Comment by antfu** [comment] 2024-08-14 12:35
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-14 12:35 UTC
Labels: pending triage
