### ISSUE TITLE
Parsing error: Unexpected token :

### ISSUE THREAD

**Issue by ProxBoss** [nuxt/eslint#490] opened 2024-08-29 12:31 UTC
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v22.5.1
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      compatibilityDate, devtools, extends, modules, sourcemap, pinia, eslint
- Runtime Modules:  @nuxt/eslint@0.5.3, @nuxt/ui, @nuxt/icon@1.5.0, @nuxtjs/tailwindcss@6.12.1, @pinia/nuxt@0.5.4, @pinia-plugin-persistedstate/nuxt@1.2.1
- Build Modules:    -
------------------------------
```

### Package

@nuxt/eslint

### Reproduction

I'm relativly new to Typescript and vue/nuxt, but I'm fairly certain this is valid syntax and code...

I keep getting "error  Parsing error: Unexpected token :" pointing to the colin before the type specifier in the function parameter list. 

### Minimal Example Component 
```
<!-- ./component/SettingsButton.vue -->
<script lang="ts" setup>
function clickHandler(event: PointerEvent) {
  console.log(event);
}
</script>

<template>
  <ClientOnly>
    <UButton
      icon="i-heroicons-cog-6-tooth-20-solid"
      color="gray"
      variant="ghost"
      aria-label="Messages"
      @click="clickHandler"
    />
    <template #fallback>
      <div class="w-8 h-8" />
    </template>
  </ClientOnly>
</template>

<style></style>

```

### eslint Result
```
node ➜ /workspaces/Notifier (Spike) $ eslint ./components/SettingsButton.vue 

/workspaces/Notifier/components/SettingsButton.vue
  3:27  error  Parsing error: Unexpected token :
✖ 1 problem (1 error, 0 warnings)
```

### Describe the bug

eslint with the  @nuxt/eslint module is incorrectly flagging ":" in function parameter lists as a parse error when used in a vue component.

e.g. the colon in the function declaration below would trigger a parse error is used in a Vue component <script> block 

```
function myFunc(input: PatamType){
}
```

### Additional context

```
//eslint.config.mjs

// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Your custom configs here
)
```

**Comment by antfu** [comment] 2024-08-29 13:31
Have you installed `typescript` in your project?

**Comment by antfu** [comment] 2024-08-29 13:31
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-29 13:31 UTC
Labels: pending triage

**Comment by ProxBoss** [comment] 2024-08-30 00:58
Thanks @antfu !!

Can confirm as you gracefully put it, it was a "userland misconfiguration" issue :grin:

For anyone with a similar issue in the future I changed my eslint.config.mjs file  as per below and everything seems to be working as expected. Seems the nuxt config doesn't enable Typescript out of the box - which caught me out.

```
// eslint.config.mjs
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    // Your custom configs here
    {
        languageOptions: {
            parserOptions: {
                parser: "@typescript-eslint/parser",
            },
        },
    }
)
```
