### ISSUE TITLE
Folder `dist` is not ignored

### ISSUE THREAD

**Issue by MickL** [nuxt/eslint#407] opened 2024-04-23 15:28 UTC
### Environment

The folder `dist` is linted if it exists. This wasnt the case before (I just upgraded from `^0.3.0-beta.9` to `0.3.9`. It should be ignored.

### Package

@nuxt/eslint

**Comment by antfu** [comment] 2024-04-23 16:18
https://github.com/nuxt/eslint/blob/28bd401e092a3c21529b592d4d088aa6148898c5/packages/eslint-config/src/flat/configs/ignores.ts#L7

**Comment by antfu** [comment] 2024-04-23 16:18
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-23 16:18 UTC
Labels: pending triage

**Comment by MickL** [comment] 2024-04-23 16:21
I understand you always need a reproduction repo but I spent SO much time already reporting various bugs within the UnJS / Nitro / Nuxt ecosystem. I cant efford the time to always create a reproduction repo.

**Comment by antfu** [comment] 2024-04-23 16:24
I can't reproduce the problem on my side thus I can't help
