### ISSUE TITLE
Upgrading from 12.0.0 to 12.1.0 cause 'Error [ERR_REQUIRE_ESM]: require() of ES Module ..... \resolveProjectList.js not supported'

### ISSUE THREAD

**Issue by LuXDAmore** [nuxt/eslint#310] opened 2023-10-02 08:35 UTC
After upgrading from `"@nuxtjs/eslint-config-typescript": "12.0.0"` to `"@nuxtjs/eslint-config-typescript": "12.1.0"` I'm facing an error during the linting, breaking ESLint:
> Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Projects\studiomado\backoffice\node_modules\globby\index.js from D:\Projects\studiomado\backoffice\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\typescript-estree\dist\parseSettings\resolveProjectList.js not supported. Instead change the require of index.js in D:\Projects\studiomado\backoffice\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\typescript-estree\dist\parseSettings\resolveProjectList.js to a dynamic import() which is available in all CommonJS modules

![Error [ERR_REQUIRE_ESM]](https://github.com/nuxt/eslint-config/assets/3841171/4d2d22e8-a95f-4c9f-9aff-c2da55e46516)

**Comment by antfu** [comment] 2024-03-19 13:40
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-19 13:40 UTC
