### ISSUE TITLE
Nuxt Deployment on DigitalOcean // ERROR  Cannot find module '/workspace/@nuxt/eslint'

### ISSUE THREAD

**Issue by simonmaass** [nuxt/eslint#448] opened 2024-06-14 14:46 UTC
### Environment

<img width="874" alt="image" src="https://github.com/nuxt/eslint/assets/32599710/8a6afa90-367c-420d-9b79-0cef42eb94bd">

### Package

@nuxt/eslint

### Reproduction

Deploy app as described in docs to digitalocean with SERVER_PRESET=digital-ocean

### Describe the bug

Get the following error in deployment:

[2024-06-14 14:17:10] │  ERROR  Error while requiring module @nuxt/eslint: Error: Cannot find module '/workspace/@nuxt/eslint'
[2024-06-14 14:17:10] │ Require stack:
[2024-06-14 14:17:10] │ - /workspace/index.js
[2024-06-14 14:17:10] │ 
[2024-06-14 14:17:10] │ 
[2024-06-14 14:17:10] │  ERROR  Cannot find module '/workspace/@nuxt/eslint'
[2024-06-14 14:17:10] │ Require stack:
[2024-06-14 14:17:10] │ - /workspace/index.js
[2024-06-14 14:17:10] │ 
[2024-06-14 14:17:10] │   Require stack:
[2024-06-14 14:17:10] │   - index.js
[2024-06-14 14:17:10] │   at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)

### Additional context

In nuxt.config.ts:
modules: ['@nuxt/eslint']

in package.json:
"devDependencies": {
    "@nuxt/eslint": "^0.3"
}

### Logs

<img width="657" alt="image" src="https://github.com/nuxt/eslint/assets/32599710/db49fc7d-3b9d-4ddb-be5e-8c6800dfbd66">

**Comment by antfu** [comment] 2024-06-15 08:16
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-06-15 08:16 UTC
Labels: pending triage
