### ISSUE TITLE
Cannot find module '[...]/.nuxt/eslint.config.mjs'

### ISSUE THREAD

**Issue by rotsee** [nuxt/eslint#431] opened 2024-05-13 09:42 UTC
### Environment

```
- Operating System: Linux
- Node Version:     v21.7.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      devtools, build, plugins, modules, vite, basicAuth
- Runtime Modules:  @kgierke/nuxt-basic-auth@1.5.0, ()
- Build Modules:    -
```

### Package

@nuxt/eslint

### Reproduction

After running `npm install --save-dev @nuxt/eslint eslint`, adding `@nuxt/eslint` to `modules` in `nuxt.config.ts` and creating a `eslint.config.mjs` file in the project root as per https://eslint.nuxt.com/packages/module, running `npx eslint .`  gives the following error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<PATH>/.nuxt/eslint.config.mjs' imported from <PATH>/eslint.config.mjs

```

The import looks like this:
`import withNuxt from './.nuxt/eslint.config.mjs'`

...and there is indeed no eslint.config.mjs file under the .nuxt directory. 

### Describe the bug

There is no `.nuxt/eslint.config.mjs` file

**Comment by antfu** [comment] 2024-05-13 09:58
Did you started the nuxt server once? Or try `nuxi prepare`

**Comment by antfu** [comment] 2024-05-13 09:58
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-13 09:58 UTC
Labels: pending triage

**Comment by rotsee** [comment] 2024-05-13 10:27
For anyone else struggling with this: It seem that the issue is related to Vuetify. If I install _first_ eslint and _then_Vuetify, then running `npx nuxi prepare`  will create the file. But if I have the recommended Vuetify setup in `nuxt.config.ts` (see below)  it does nothing (and `nuxi module add eslint` throws a bunch of errors saying: `Casting "BlockStatement" is not supported`).

This is the recommended way to enable Vuetify, that seems to prevent eslint installation:
```
  modules: [
    (_options, nuxt) => {
      nuxt.hooks.hook('vite:extendConfig', (config) => {
        // @ts-expect-error
        config.plugins.push(vuetify({ autoImport: true }))
      })
    },
  ],
  ```
  
  A workaround is to remove the whole Vuetify block from the config, run `nuxi prepare`, and then re-add Vuetify.

**Comment by avestura** [comment] 2024-12-24 16:25
It looks like Nuxt removes all of the unknown generated files inside the `.nuxt` folder after all of the modules have done their work. Hence why the `.nuxt/eslint.config.mjs` is immediately deleted after the `nuxi prepare` finishes.

I don't know much about the internals of Nuxt Kit, but it looks like one fix would be to introduce this file using `addTemplate` just like how it is done for the `eslint.config.d.mts`. In short, this line:

https://github.com/nuxt/eslint/blob/01dd3e8c6e147a0b64e56babf8d62feb7ac97f37/packages/module/src/modules/config/index.ts#L46

Should be replaced with:

```js
  addTemplate({
    filename: configFile,
    write: true,
    getContents() {
      return code;
    }
  });
```

I've tested it on my local machine, and it worked. Any thoughts? @antfu

**Comment by acuteaura** [comment] 2025-06-04 07:33
It was the workaround from here: https://github.com/nuxt/cli/issues/169

Just turn off `typeCheck` and move on, it causes all sorts of bugs in the build.
