### ISSUE TITLE
After update from 0.4.0 to 0.5.0: no-unused-vars returns TypeError: Cannot use 'in' operator to search for 'type' in undefined

### ISSUE THREAD

**Issue by TimGuendel** [nuxt/eslint#472] opened 2024-08-05 09:52 UTC
### Environment

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.3.0
- Builder:          -
- User Config:      telemetry, experimental, components, nitro, imports, vite, css, devtools, debug, modules, pinia, postcss, cookieControl, runtimeConfig, compatibilityDate
- Runtime Modules:  @vueuse/nuxt@10.11.0, @pinia/nuxt@0.5.2, @pinia-plugin-persistedstate/nuxt@1.2.1, nuxt-jsonld@2.0.8, @nuxt/image@1.7.0, @zadigetvoltaire/nuxt-gtm@0.0.13, @dargmuesli/nuxt-cookie-control@8.4.6, @nuxt/test-utils/module@3.13.1, @nuxt/eslint@0.5.0, @vee-validate/nuxt@4.13.2

### Package

@nuxt/eslint

### Reproduction

N/A

### Describe the bug

After updating from 0.4.0 to 0.5.0: no-unused-vars returns 

`TypeError: Cannot use 'in' operator to search for 'type' in undefined.`

Line 133 is always the first line after <script setup lang="ts">

**Comment by antfu** [comment] 2024-08-19 10:11
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-19 10:11 UTC
Labels: pending triage

**Comment by zigcccc** [comment] 2024-08-30 07:58
I'm seeing this as well:
<img width="566" alt="image" src="https://github.com/user-attachments/assets/f11be4cf-a81a-435e-ae13-ed132c498ae2">

It's not happening in all files, just some.

TS version: `~5.3.3`
typescript-eslint: `^8.2.0`
eslint-plugin-unused-imports: `^4.1.3`

**Comment by TimGuendel** [comment] 2024-08-30 08:01
I too am stil getting this error. This is the whole message:

```
[info] Using yup with vee-validate
[success] Types generated in .nuxt

Oops! Something went wrong! :(

ESLint: [9](https://github.com/ecommercedb/frontend-web-2/actions/runs/10628890600/job/29464609458?pr=610#step:4:10).9.1

TypeError: Cannot use 'in' operator to search for 'type' in undefined
Occurred while linting /home/runner/work/frontend-web-2/frontend-web-2/components/charts/ChartContainer.vue:[13](https://github.com/ecommercedb/frontend-web-2/actions/runs/10628890600/job/29464609458?pr=610#step:4:14)3
Rule: "@typescript-eslint/no-unused-vars"
    at UnusedVarsVisitor.markVariableAsUsed (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables.js:92:22)
    at UnusedVarsVisitor.TSMappedType (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@nuxt/eslint-config/node_modules/@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables.js:235:[14](https://github.com/ecommercedb/frontend-web-2/actions/runs/10628890600/job/29464609458?pr=610#step:4:15))
    at UnusedVarsVisitor.visit (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:59:21)
    at UnusedVarsVisitor.visitChildren (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:46:22)
    at UnusedVarsVisitor.visit (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:64:14)
    at UnusedVarsVisitor.visitChildren (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:46:22)
    at UnusedVarsVisitor.visit (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:64:14)
    at UnusedVarsVisitor.visitChildren (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:46:[22](https://github.com/ecommercedb/frontend-web-2/actions/runs/10628890600/job/29464609458?pr=610#step:4:23))
    at UnusedVarsVisitor.visit (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:64:14)
    at UnusedVarsVisitor.visitChildren (/home/runner/work/frontend-web-2/frontend-web-2/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:41:30)
Error: Process completed with exit code 2.
```

**Comment by TimGuendel** [comment] 2024-09-10 13:27
If it helps, this is the same error: https://github.com/typescript-eslint/typescript-eslint/issues/9719
I am still getting it when updating from "@nuxt/eslint": "^0.4.0" to "@nuxt/eslint": "^0.5.6"

**Comment by hugotiburtino** [comment] 2024-09-11 16:28
Same here

Reproduction steps:
1. [Clone `serlo/api.serlo.org`, go to the branch of this PR ](https://github.com/serlo/api.serlo.org/pull/1730) and run `yarn`
2. Add `"@typescript-eslint/no-duplicate-enum-values": "off",` to `.eslintrc.json` (to avoid another very strange error)
3. Run `yarn list:eslint`

**Comment by TimGuendel** [comment] 2024-09-12 06:59
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

So can this be reopened? 🤔

**Comment by deim0707** [comment] 2024-10-28 13:44
It's still relevant today.

**Comment by antfu** [comment] 2024-10-28 14:19
This seems to be an upstream issue with ts-eslint, yet there doesn't seem to be a valid minimal reproduction here or even in https://github.com/typescript-eslint/typescript-eslint/issues/9719

If you do find a minimal reproduction, please open a new issue.

**Comment by nwparker** [comment] 2024-10-28 17:22
Try updating your `@typescript-eslint/*` dependencies, this helped for me

**Comment by vaynevayne** [comment] 2024-11-13 03:39
> Try updating your `@typescript-eslint/*` dependencies, this helped for me

newest is 8.14.0, issue is still exist

**Comment by TimGuendel** [comment] 2024-11-15 09:21
Same for me - just updated from 0.4.0 to 0.6.1.

**Comment by vaynevayne** [comment] 2024-12-06 01:37
uninstall `eslint-plugin-unused-imports` , issue is  disappear , 
The reason why you came into existence also comes from `eslint-plugin-unused-imports` ?

**Comment by pranavmappoli** [comment] 2024-12-07 14:12
Any update on the issue ?
