### ISSUE TITLE
Conflicting with @vue/eslint-config-typescript > 11.0.2

### ISSUE THREAD

**Issue by MartinX3** [nuxt/eslint#280] opened 2023-04-25 17:41 UTC
Since v11.0.3 of @vue/eslint-config-typescript I get the following error:
```
Oops! Something went wrong! :(

ESLint: 8.39.0

ESLint couldn't determine the plugin "@typescript-eslint" uniquely.

- /home/developer/node_modules/.pnpm/@typescript-eslint+eslint-plugin@5.59.1_@typescript-eslint+parser@5.59.1_eslint@8.39.0_typescript@5.0.4/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in ".eslintrc.js » @vue/eslint-config-typescript/recommended » plugin:@typescript-eslint/recommended » ./configs/base")
- /home/developer/node_modules/.pnpm/@typescript-eslint+eslint-plugin@5.56.0_@typescript-eslint+parser@5.56.0_eslint@8.39.0_typescript@5.0.4/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in ".eslintrc.js » @nuxtjs/eslint-config-typescript")

Please remove the "plugins" setting from either config or remove either plugin installation.
```

**Comment by danielroe** [comment] 2023-04-25 18:15
I'll take a look, but note that you should not need both configs.

**Comment by MartinX3** [comment] 2023-04-26 07:18
@danielroe oh, i thought I need both in my vuetify nuxt bridge project.
Especially since this repo is months old and doesn't tell mw not to use it in the readme.

**Comment by MartinX3** [comment] 2023-05-11 16:48
@danielroe 
Any update on this and my questions?
(I thought this plugin uses `@vue/eslint-config-typescript` as a base)

**Comment by antfu** [comment] 2024-03-19 13:49
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-19 13:49 UTC
Labels: nuxt2-legacy
