### ISSUE TITLE
Stylistic rules do not apply

### ISSUE THREAD

**Issue by zecar** [nuxt/eslint#412] opened 2024-04-26 09:53 UTC
### Environment

- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      srcDir, devtools, components, modules, eslint, ignore, appConfig, css, extensions, ssr, routeRules, vue, nitro, runtimeConfig, auth, colorMode, router, csurf, content
- Runtime Modules:  @nuxt/eslint@0.3.10, @nuxt/test-utils/module@3.12.1, @unocss/nuxt@0.59.4, @sidebase/nuxt-auth@0.7.2, @nuxt/ui@2.15.2, @pinia/nuxt@0.5.1, @nuxt/content@2.12.1, nuxt-csurf@1.5.2
- Build Modules:    -

### Package

@nuxt/eslint

### Reproduction

```
{
eslint: {
    config: {
      stylistic: {
        indent: 2,
        quotes: 'single',
        semi: false,
        commaDangle: 'never',
      },
    },
  },
}
```

### Describe the bug

i've just installed the @nuxt/eslint module and put this config in nuxt.config.ts

when I run `eslint nuxt.config.ts` nothing changes.. commaDongle is still present, semi-colon is still there

### Additional context

eslint.config.mjs
```
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  "rules": {
    "vue/multi-word-component-names": "off",
    "no-case-declarations": "warn",
    "no-console": "off",
    "vue/no-multiple-template-root": "off",
    "no-unused-expressions": "off",
    "@typescript-eslint/no-unused-vars": "warn"
  }
})

```

**Comment by antfu** [comment] 2024-04-29 09:00
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by 719media** [comment] 2024-05-08 20:53
@antfu I'm having the same problem. I tried to make commits according to the "repository installation" steps:

1. `npx nuxi@latest init`
2. `npx nuxi module add eslint`
3. `npm install --save-dev vue-tsc@^1 typescript` (I probably should have skipped this step to isolate typescript array from the issues...)
4. Adding simple eslint stylistic rule as indicated on https://eslint.nuxt.com/packages/module#eslint-stylistic
5. Add an example page with bad linting

At this point, running `npm run lint` or `npm run lint:fix` does not have the desired outcome

https://github.com/719media/nuxt_test_lint

**Comment by 719media** [comment] 2024-05-08 21:25
I just did this again now to make sure I got any changes from any repositories from the last day or two. And without step 3 (typescript). Same result. However, if I `rm -rf package-lock.json` and `rm -rf node_modules` and then `npm install`, it starts working. The changes at this point to package-lock.json is quite extensive, so not sure it helps to paste it all.

**Comment by zecar** [comment] 2024-05-09 06:45
i've bypassed this by putting the stylistic config inside eslint config file instead of nuxt config

**Comment by antfu** [comment] 2024-05-09 12:54
I couldn't reproduce this with the given repo - it sounds like a dependencies duplication issue, please try to bump deps rebuild the locks. If you still have this issue, please create a new issue with a minimal reproduction. Thank you,

**Closed by antfu** 2024-05-09 12:54 UTC
Labels: pending triage

**Comment by Amar-Gill** [comment] 2024-08-25 17:48
I was having the same problem.

Migrated from eslint v8 config to eslint v9 flat config. Was hoping to move deprecated eslint rules like `quotes`, `quoteProps`, `commaDangle` into my `nuxt.config.ts` file, using associated stylistic rules.

Was confused why auto-formatting kept writing double quotes when my stylistic rule was `quotes: 'single'`.

What worked for me:

```bash
rm -rf .nuxt/ node_modules/
rm pnpm-lock.yaml
pnpm i
```

Restarted editor and auto-formatting is now working correctly.
