### ISSUE TITLE
vue parsing error

### ISSUE THREAD

**Issue by Vijay-eZee** [nuxt/eslint#167] opened 2021-07-12 05:48 UTC
[Steps]
1. Install @nuxtjs/eslint-config-typescript: "^6.0.1" and @typescript-eslint/eslint-plugin: "^4.28.1"
2. Extends in eslint configuration file
   extends: [
    '@nuxtjs/eslint-config-typescript',
   'plugin:@typescript-eslint/recommended',
  ]
 [Currrent]
 1. Generate vue parsing error(ref screen shote attach here 
 
![eslint_vue_parser_error](https://user-images.githubusercontent.com/60382741/125237067-b4576c00-e302-11eb-8e2e-0308980ef77e.png)
[Expect]
1. Should parse .vue file also

**Comment by antfu** [comment] 2024-03-19 13:44
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-19 13:44 UTC
