### ISSUE TITLE
Add plugins to peer deps

### ISSUE THREAD

**Issue by ExEr7um** [nuxt/eslint#266] opened 2023-01-20 08:59 UTC
There are 3 plugins in `package.json`:
- `@typescript-eslint/eslint-plugin`
- `@typescript-eslint/parser`
- `eslint-plugin-vue`

Shouldn't we add them to peer dependencies? Because I still need to install all of them, which is not stated in documentation.

If we add them to peer deps, users will be able to only install `@nuxt/eslint-config`.

**Comment by antfu** [comment] 2024-03-19 13:41
I am not sure what do you mean - that are already in "dependencies" which should work.

Otherwise please provide a minimal reproduction, thanks.

**Comment by antfu** [comment] 2024-03-19 13:41
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-19 13:41 UTC

**Comment by ExEr7um** [comment] 2024-03-20 07:46
I think it was fixed somewhere down the line. Issue should be closed now, thanks!
