### ISSUE TITLE
Missing assets in config viewer

### ISSUE THREAD

**Issue by davidurco** [nuxt/eslint#355] opened 2024-03-22 08:45 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr, app, css, vite, modules, eslint, i18n, postcss, googleFonts, apollo, colorMode, runtimeConfig, devtools
- Runtime Modules:  @nuxt/eslint@0.3.0-beta.3, @nuxtjs/apollo@5.0.0-alpha.13, @nuxtjs/i18n@8.1.1, @nuxtjs/tailwindcss@6.11.3, @nuxtjs/color-mode@3.3.2, @nuxtjs/google-fonts@3.1.3, floating-vue/nuxt, @pinia/nuxt@0.5.1, nuxt-icons@3.2.1
- Build Modules:    -
------------------------------

### Package

@nuxt/eslint

### Reproduction

Follow the official setup guide and then try to run config viewer by running `npx eslint-flat-config-viewer`.

### Describe the bug

When I open eslint config viewer by running `npx eslint-flat-config-viewer`, I get two 404 in the console.

```
GET http://127.0.0.1:8123/_nuxt/Users/antfu/i/eslint-flat-config-viewer/node_modules/.pnpm/nuxt@3.11.1_@unocss+reset@0.58.6_eslint-ts-patch@8.57.0-0_floating-vue@2.0.0-beta.24_fuse.js@_kx2jdcqznuisdn6rxdbdpjbnl4/node_modules/nuxt/dist/app/entry.js net::ERR_ABORTED 404 (Cannot find static asset /_nuxt/Users/antfu/i/eslint-flat-config-viewer/node_modules/.pnpm/nuxt@3.11.1_@unocss+reset@0.58.6_eslint-ts-patch@8.57.0-0_floating-vue@2.0.0-beta.24_fuse.js@_kx2jdcqznuisdn6rxdbdpjbnl4/node_modules/nuxt/dist/app/entry.js)
configs:5 
        
        
GET http://127.0.0.1:8123/_nuxt/@vite/client net::ERR_ABORTED 404 (Cannot find static asset /_nuxt/@vite/client)
```

**Comment by antfu** [comment] 2024-03-25 08:58
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-25 08:58 UTC
Labels: pending triage
