### ISSUE TITLE
Parsing error on jsx.

### ISSUE THREAD

**Issue by mathieutu** [nuxt/eslint#123] opened 2020-10-21 11:51 UTC
Hi folks, 

I have a parsing issue with some jsx:
<img width="815" alt="Screenshot 2020-10-21 at 12 47 48" src="https://user-images.githubusercontent.com/11351322/96712341-45666b80-139f-11eb-981b-2ef803624cdd.png">

My script tag has `lang="jsx"`, my eslint config is the following:

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
  },
  extends: [
    '@nuxtjs/eslint-config-typescript',
    'plugin:nuxt/recommended',
  ],
}

```

Do you have any idea of what could be the problem?

Thanks!

**Comment by antfu** [comment] 2024-03-19 13:49
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-19 13:49 UTC
Labels: nuxt2-legacy
