### ISSUE TITLE
Stylistic config ignored

### ISSUE THREAD

**Issue by davidurco** [nuxt/eslint#356] opened 2024-03-22 08:48 UTC
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      ssr, app, css, vite, modules, eslint, i18n, postcss, googleFonts, apollo, colorMode, runtimeConfig, devtools
- Runtime Modules:  @nuxt/eslint@0.3.0-beta.3, @nuxtjs/apollo@5.0.0-alpha.13, @nuxtjs/i18n@8.1.1, @nuxtjs/tailwindcss@6.11.3, @nuxtjs/color-mode@3.3.2, @nuxtjs/google-fonts@3.1.3, floating-vue/nuxt, @pinia/nuxt@0.5.1, nuxt-icons@3.2.1
- Build Modules:    -
------------------------------

### Package

@nuxt/eslint

### Reproduction

Follow the official setup guide and then set some stylistic rules, for example:
```
  eslint: {
    config: {
      stylistic: {
        jsx: false,
        commaDangle: 'never',
        indent: 6,
      },
    },
  },
```

### Describe the bug

Stylistic rules in nuxt config are ignored. When I run `eslint .` I see errors like `7:1   error  Expected indentation of 2 spaces but found 1 tab   @stylistic/indent`, even though I specified `indent: 6` in nuxt config.

**Comment by DamianGlowala** [comment] 2024-03-22 09:43
Have you restarted your Nuxt project and reloaded VS Code window? This is working fine for me.

**Comment by antfu** [comment] 2024-03-25 08:58
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-25 08:58 UTC
Labels: pending triage

**Comment by davidurco** [comment] 2024-03-25 08:59
I can confirm now that it works. But code editor needs to be restarted after every change to eslint config in nuxt config.
