### ISSUE TITLE
eslint/config-inspector custom host/port when using @nuxt/eslit

### ISSUE THREAD

**Issue by Meas** [nuxt/eslint#443] opened 2024-05-23 23:44 UTC
### Describe the feature

Sorry to bother, this may be the lowest priority thing ever and possibly it is already implemented. 

I am having issues accessing the eslint/config-inspector using a docker container when using @nuxt/eslint plugin. I just created a fresh project. Is there a way to set something like this:
```
//nuxt.config.ts
export default defineNuxtConfig({
modules: [
  ["@nuxt/eslint", {devServer: {host: "0.0.0.0"}]
]
```
Or is there already something that can accomplish something similar?

Thanks in advanced!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/eslint/discussions) and [issues](https://github.com/nuxt/eslint/issues).

**Comment by antfu** [comment] 2024-05-25 11:00
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-25 11:00 UTC
Labels: pending triage

**Comment by Jan-Heussner** [comment] 2024-10-10 12:42
I have the same issue.

I am running nuxt in a docker container with providing `NUXT_HOST=0.0.0.0 `and everything is working fine to far.

After installing  `@nuxt/eslint": "^0.5.7` the linter works fine.

When i run `npx @eslint/config-inspector `the terminal stucks with 
`ℹ Starting ESLint config inspector at http://localhost:7777 `

If i run the same command with `--host 0.0.0.0` everything works fine.
On terminal i could run it like this for sure, but in case of the Nuxt Dev Tools i have no Idea how tho provide the host.

**Comment by Jan-Heussner** [comment] 2024-10-11 15:47
@antfu: can u add the host here? from my point of view it would make sense to set the host there and consume from NUXT_HOST which can be not only localhost.

https://github.com/nuxt/eslint/blob/c7372bd52462b89d63fc5db5dc04eaa8169ce942/packages/module/src/modules/config/devtools.ts#L48
